<?php

/**
 * Implements hook_install().
 */
function ai_provider_litellm_install() {
  if (!module_load_install('ai_upgrade')) { return []; }
  ai_upgrade_module_install('ai_provider_litellm');
}

/**
 * Implements hook_uninstall().
 */
function ai_provider_litellm_uninstall() {
  config('ai_provider_litellm.settings')->delete();
}

/**
 * Implements hook_requirements().
 */
function ai_provider_litellm_requirements($phase) {
  if (!module_load_install('ai_upgrade')) { return []; }
  return ai_upgrade_module_requirements($phase, 'ai_provider_litellm');
}
